= Comment vaincre l'amour ?

La langue française est souvent précise, c'est d'ailleurs pour cela qu'elle est la langue de la diplomacie. Son lexique est riche. Mais pas assez riche à mon goût ! Parlons d'amour, mais quel amour ? Il en existe au moins 2 :

- L'amour chimique
- L'amour vrai



== Pourquoi cette question ?
L'amour chimique est une maladie, la "maladie d'amour", celui qui nous aveugle, celui qui nous fait voir l'autre comme beau lorsqu'il ne l'ai pas, comme gentil lorsqu'il est méchant, comme aimant lorsqu'il n'aime pas. Il nous empêche de voir les défauts de l'autre. Est ce grave ? Tout le monde a des défauts. Le problème est que notre corps nous impose l'autre dans le seul but de procréer. Tant mieux pour l'espèce humaine. Toutefois cela se termine souvent en catastrophe, une fois que l'alchimie disparait, les incompatibilités deviennent des poisons, le couple se désagrege, souvent dans la douleur, les cris et les larmes. Et si seulement ! Si seulement nous avions pu *choisir*, en toute objectivité, en pleine conscience. Connaitre nos incompatibilités et en juger sans émotions. Aimer l'autre pour ce qu'il est et non pour ce qu'on ressent au début de la relation.


== Que faire ?
