= Comment vaincre l'amour ?

La langue française est souvent précise, c'est d'ailleurs pour cela qu'elle est la langue de la diplomacie. Son lexique est riche. Mais pas assez riche à mon goût ! Parlons d'amour, mais quel amour ? Il en existe au moins 2 :

- L'amour-chimie
- L'amour-vrai


== Pourquoi cette question ?
L'amour-chimie est une maladie, la "maladie d'amour", celle qui nous aveugle, celle qui nous fait voir l'autre comme beau lorsqu'il ne l'ai pas, comme gentil lorsqu'il est méchant, comme aimant lorsqu'il n'aime pas. Elle nous empêche de voir les défauts de l'autre. Est ce grave ? Tout le monde a des défauts. Le problème est que notre corps nous impose cet autre dans le seul but de procréer; de perpétuer l'espèce. Tant mieux pour l'espèce humaine. Toutefois cela se termine souvent en catastrophe, une fois que l'alchimie disparait, les incompatibilités deviennent des poisons, le couple se désagrege, souvent dans la douleur, les cris et les larmes. 

Et si seulement ! Si seulement nous pouvions *choisir*, en toute objectivité, en pleine conscience. Connaitre nos incompatibilités et en juger sans émotion. Aimer l'autre pour ce qu'il *est* et non pour ce qu'on ressent au début de la relation. Aimer vraiment d'un amour vrai, sans influence. Peut-être pourrions-nous augmenter nos chances d'être heureux en couple ?


== Que faire ?
Encore une fois, vous ne trouverez pas de réponse ici. Lorsque nous amis nous disent "Tu sais, je ne pense pas qu'il soit fait pour toi", on s'en fiche. Lorsqu'il nous disent "Vous vous disputez trop, ça ne présage rien de bons", on s'en fiche ! "Il n'est pas fait pour toi !" Je m'en FICHE. Et ça, c'est quand on a la chance d'avoir de vrais amis, ceux qui nous disent la vérité, ceux qui n'ont pas de filtre.

Peut être après la lecture de cet article vous vous direz que maintenant vous êtes conscient, conscient de cette maladie et que vous irez vous-même demander l'avis de vos amis et prendre en compte leurs avis. Je l'ai fait et on m'a dit "Elle est pas mal" pour me dire "Elle est moche !!" et moi j'ai compris "Elle est jolie". On m'a dit "Elle a du caractère", j'ai compris "Elle a du charme", on a voulu me dire "Elle est relou, fuit". Ont il mis des filtres ? Pourtant j'ai demandé à ceux qui ont le moins de filtre, ceux dont je savais qu'il me dirait la vérité. En réalité, il me l'ont dit mais j'ai interprété, j'ai vu le verre à moitié plein. Putain d'optimisme !

La solution est t'elle de connaitre avant de se mettre en couple ? J'ai cette amie, qui est sortie avec un de ses  meilleurs amis. Ils se connaissent parfaitement, se sont choisis. Ils me disent s'aimer, cet amour ne peut être qu'un amour vrai. Mais un amour vrai sans coup de foudre, sans lune de miel, sans début, sans charme. Une autre amie, petite amie cette fois m'a confié avoir quitté son ex au bout de 5 années parcequ'elle savait ne l'avoir jamais aimé. En fait, elle n'avait jamais eu d'amour-chimie avec lui, elle l'avait choisi, l'avait aimé d'un amour-vrai et l'avait quitté par manque de ce "truc" fabuleux que tout le monde cherche. Je n'ai jamais vraiment osé lui dire clairement qu'elle était sans doute dans l'erreur. 

Doit-on attendre que l'amour-chimie disparaisse ? Cette amour se dissipe au bout de quelques années et ne disparait vraiment qu'à la naissance d'un enfant. Souhaitez-vous vraiment attendre 2 ou 3 ans avant de vous engager ? Ou mettre un enfant qui n'a rien demandé dans la balance ? Dans le premier cas, votre conjoint va s'impatienter, sur de ses propres sentiments et de son choix, dans le second vous allez rendre votre enfant malheureux d'avoir des parents soit malheureux, soit séparés.

Pouvons-nous avoir à coup sûr un amour-vrai et durable après un coup de foudre ? Peut-on compenser l'absence du coup de foudre pour quelqu'un que l'on a choisi objectivement et que l'on aime vraiment ?

